name: Deploy on Docker Hub

on:
  # cuando se haga push a main
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: code-checkout
        uses: actions/checkout@v4
      # Se encarga de iniciar sesion en Docker hub
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build n push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/buhosapp:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/buhosapp:${{ github.sha }}